using System.Globalization;
using PortfolioTradingSystem.Domain.Enums;
using PortfolioTradingSystem.Domain.Models;
using PortfolioTradingSystem.Domain.Strategy;
using Xunit;

namespace PortfolioTradingSystem.Tests;

/// <summary>
/// Replays real daily bars through <see cref="MomentumEngineState"/> and compares the
/// resulting trades with the ones the Python simulator produces on exactly the same
/// input (Fixtures/sber_trades.csv, generated by strategy_research.py).
///
/// This is the test that would have caught the defect this branch fixes: the research
/// simulator opened a new position at the OPEN of a bar on which the previous position
/// had just been stopped out, and the C# engine reproduced it. A parity harness makes
/// the two implementations state the same rule out loud.
/// </summary>
public class ResearchParityTests
{
    private sealed record ExpectedTrade(
        DateOnly EntryDate, DateOnly ExitDate, int Direction, int Units,
        decimal Entry, decimal Exit, string Reason, decimal Pnl);

    private static StrategyOptions ResearchOptions() => new()
    {
        RocBars = 5,
        RocThreshold = 0.01m,
        AtrPeriod = 14,
        SlAtr = 2.0m,
        TpAtr = 3.0m,
        RiskPct = 10.0m,
        CommissionPct = 0.04m,
        PointRub = 1.0m,
        Leverage = 1.0m,
        InitialCapital = 100_000m,
        ShortsEnabled = true,
    };

    private static string FixturePath(string name) =>
        Path.Combine(AppContext.BaseDirectory, "Fixtures", name);

    private static List<Candle> LoadBars()
    {
        var bars = new List<Candle>();
        foreach (string line in File.ReadLines(FixturePath("sber_bars.csv")).Skip(1))
        {
            string[] parts = line.Split(',');
            var day = DateOnly.ParseExact(parts[0], "yyyy-MM-dd", CultureInfo.InvariantCulture);
            bars.Add(new Candle(
                new DateTimeOffset(day.ToDateTime(new TimeOnly(10, 0)), TimeSpan.FromHours(3)),
                decimal.Parse(parts[1], CultureInfo.InvariantCulture),
                decimal.Parse(parts[2], CultureInfo.InvariantCulture),
                decimal.Parse(parts[3], CultureInfo.InvariantCulture),
                decimal.Parse(parts[4], CultureInfo.InvariantCulture),
                0L));
        }

        return bars;
    }

    private static List<ExpectedTrade> LoadExpected()
    {
        var trades = new List<ExpectedTrade>();
        foreach (string line in File.ReadLines(FixturePath("sber_trades.csv")).Skip(1))
        {
            string[] p = line.Split(',');
            trades.Add(new ExpectedTrade(
                DateOnly.ParseExact(p[0], "yyyy-MM-dd", CultureInfo.InvariantCulture),
                DateOnly.ParseExact(p[1], "yyyy-MM-dd", CultureInfo.InvariantCulture),
                int.Parse(p[2], CultureInfo.InvariantCulture),
                int.Parse(p[3], CultureInfo.InvariantCulture),
                decimal.Parse(p[4], CultureInfo.InvariantCulture),
                decimal.Parse(p[5], CultureInfo.InvariantCulture),
                p[6],
                decimal.Parse(p[7], CultureInfo.InvariantCulture)));
        }

        return trades;
    }

    /// <summary>
    /// One daily bar of the research loop: manage the open position against this bar
    /// (signal_reversal first - close at the open - then SL/TP), then - only if that
    /// did not just close it OR it was a reversal flip - enter at this bar's open on
    /// the previous bar's signal, then finalize the bar. This mirrors strategy_research.py
    /// exactly, including the reversal exception to the no-entry-on-exit-bar rule.
    /// </summary>
    private static List<TradeClosedEvent> Replay(IReadOnlyList<Candle> bars, MomentumEngineState state)
    {
        var trades = new List<TradeClosedEvent>();
        foreach (var bar in bars)
        {
            var closed = state.TryCloseOnReversal(bar.Open, bar.Time);
            if (closed is null)
            {
                closed = state.CheckStop(bar.High, bar.Low, bar.Time, bar.Open);
            }

            if (closed is not null)
            {
                trades.Add(closed);
            }

            if (closed is null || closed.Reason == ExitReason.SignalReversal)
            {
                state.TryOpen(bar.Open, bar.Time);
            }

            state.FinalizeDay(bar);
        }

        if (state.Position is not null)
        {
            trades.Add(state.ClosePosition(bars[^1].Close, ExitReason.System, bars[^1].Time));
        }

        return trades;
    }

    [Fact]
    public void TradesMatchThePythonSimulatorOnTheSameBars()
    {
        var bars = LoadBars();
        var expected = LoadExpected();
        Assert.Equal(300, bars.Count);
        Assert.NotEmpty(expected);

        var actual = Replay(bars, new MomentumEngineState(ResearchOptions(), "SBER"));

        Assert.Equal(expected.Count, actual.Count);
        for (int i = 0; i < expected.Count; i++)
        {
            ExpectedTrade e = expected[i];
            TradeClosedEvent a = actual[i];
            string at = $"trade #{i} ({e.EntryDate:yyyy-MM-dd} -> {e.ExitDate:yyyy-MM-dd})";

            Assert.True(e.EntryDate == DateOnly.FromDateTime(a.EntryTime.DateTime), at + " entry date");
            Assert.True(e.ExitDate == DateOnly.FromDateTime(a.ExitTime.DateTime), at + " exit date");
            Assert.True(e.Direction == (int)a.Direction, at + " direction");
            Assert.True(e.Units == a.Units, at + $" units: {e.Units} vs {a.Units}");
            AssertClose(e.Entry, a.EntryPrice, 1e-6m, at + " entry price");
            AssertClose(e.Exit, a.ExitPrice, 1e-4m, at + " exit price");
            AssertClose(e.Pnl, a.PnlRub, 0.05m, at + " pnl");
        }
    }

    [Fact]
    public void TradeNeverEntersOnAnExitBarUnlessItIsAReversalFlip()
    {
        var bars = LoadBars();
        var trades = Replay(bars, new MomentumEngineState(ResearchOptions(), "SBER"));

        // The defect this guards against: an exit and an entry sharing one bar, the
        // entry filled at that bar's open - a price that was gone by the time the
        // stop or target was hit. The ONE exception is a signal_reversal flip, whose
        // close and re-entry both fill at the same open.
        for (int i = 1; i < trades.Count; i++)
        {
            if (trades[i].EntryTime <= trades[i - 1].ExitTime)
            {
                Assert.True(
                    trades[i - 1].Reason == ExitReason.SignalReversal,
                    $"trade #{i} enters at {trades[i].EntryTime:yyyy-MM-dd}, "
                    + $"the previous one exited at {trades[i - 1].ExitTime:yyyy-MM-dd} "
                    + $"with reason {trades[i - 1].Reason}");
            }
            else
            {
                Assert.True(
                    trades[i].EntryTime > trades[i - 1].ExitTime,
                    $"trade #{i} enters at {trades[i].EntryTime:yyyy-MM-dd}, "
                    + $"the previous one exited at {trades[i - 1].ExitTime:yyyy-MM-dd}");
            }
        }
    }

    private static void AssertClose(decimal expected, decimal actual, decimal tolerance, string because)
    {
        decimal scale = Math.Max(1m, Math.Abs(expected));
        Assert.True(
            Math.Abs(expected - actual) <= tolerance * scale,
            $"{because}: expected {expected}, got {actual}");
    }
}
